name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  First-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout steps
        uses: actions/checkout@v4
      - name: list files
        run: ls
        shell: bash
