name: ci workflow
on:
    push

jobs:
    ci-workflow:
        name: ci workflow
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v4

            - name: build the app  
              run: "mvn clean package"
              shell: bash
            - name: build the app  
              run: "mvn test"
              shell: bash
