name: ci workflow
on:
    push

jobs:
    ci-workflow:
        name: ci workflow
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
            - name: Run the Maven verify phase
              run: mvn --batch-mode --update-snapshots verify

            - name: Set up JDK 11 for x64
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
                architecture: x64

            - name: clean code 
              run: mvn clean package
              shell: bash
            
            - name: test code 
              run: mvn test package
              shell: bash 