name: ci workflow
on:
    push

jobs:
    ci-workflow:
        name: ci workflow
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v4
  
            - name: Set up JDK 11 for x64
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
                architecture: x64

            - name: test the app  
              run: mvn test
              shell: bash
